image: java:8

pipelines:
  default:
    - step:
        caches:
          - gradle
          - maven
        script: 
          - bash ./gradlew clean build
          - curl -vX POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"web/build/libs/web.jar"