
spring:
  application:
    name: "Texaco web app"
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:hsqldb:mem:tmp
    username: user
    password: pass
    driver-class-name: org.hsqldb.jdbc.JDBCDriver

server:
  display-name: "Texaco web app"


logging:
  level:
#    "org.springframework.boot.autoconfigure.logging": DEBUG

