
spring:
  application:
    name: "Texaco web app"
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:hsqldb:mem:tmp
    #url: jdbc:hsqldb:file:/tmp/db/db;shutdown=true
    username: user
    password: pass
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa.hibernate.ddl-auto: none

server:
  display-name: "Texaco web app"

texaco:
  #processor.classifier.dir: /tmp/learned-data/

logging:
  level:
#    "org.springframework.boot.autoconfigure.logging": DEBUG

